apiVersion: skaffold/v2beta24
kind: Config
metadata:
  name: email-service
build:
  artifacts:
    - image: company/email-service
      buildpacks:
        builder: gcr.io/paketo-buildpacks/builder:base
        env:
          - BP_JVM_VERSION=17.*
deploy:
  kustomize:
    paths:
      - k8s
