server:
  port: 9003

spring:
  application:
    name: email-service
  config:
    import: "optional:configserver:"
  mail:
    host:
    port:
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  cloud:
    bus:
      enabled: false
    config:
      uri: http://localhost:8888
      username: user
      password: password
      request-connect-timeout: 2000 # 2s
      request-read-timeout: 5000 # 5s
      fail-fast: false
      retry:
        max-attempts: 6
        initial-interval: 1000 # 1s
        max-interval: 2000 # 2s
        multiplier: 1.1

    stream:
      default:
        contentType: application/json
      bindings:
        messageProcessor-in-0:
          destination: email
          group: emailGroup

        messageProcessor-in-0.consumer:
          maxAttempts: 3
          backOffInitialInterval: 500
          backOffMaxInterval: 1000
          backOffMultiplier: 2.0

      rabbit:
        bindings:
          messageProcessor-in-0.consumer:
            autoBindDlq: true
            republishToDlq: true

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    connection-timeout: 5s
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411/}

info:
  system: Subscription System

management:
  endpoints:
    web:
      exposure:
        include: health, heapdump, info, prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
